# Generated by Django 3.2.8 on 2021-10-25 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('masurement_value', models.CharField(choices=[('шт.', 'шт.'), ('звездочка', 'звездочка'), ('г', 'г'), ('пучок', 'пучок'), ('по вкусу', 'по вкусу'), ('мл', 'мл'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('пакет', 'пакет'), ('долька', 'долька'), ('упаковка', 'упаковка'), ('щепотка', 'щепотка'), ('стручок', 'стручок'), ('зубчик', 'зубчик'), ('банка', 'банка'), ('стебель', 'стебель'), ('веточка', 'веточка'), ('кг', 'кг'), ('тушка', 'тушка'), ('лист', 'лист'), ('пласт', 'пласт'), ('горсть', 'горсть'), ('ч. л.', 'ч. л.'), ('капля', 'капля'), ('пачка', 'пачка'), ('л', 'л'), ('ст. л.', 'ст. л.'), ('пакетик', 'пакетик'), ('батон', 'батон'), ('бутылка', 'бутылка')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('time_cooking', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('Черный', '#000000'), ('Серый', '#808080'), ('Серебряный', '#c0c0c0'), ('Белый', '#ffffff'), ('Фуксия', '#ff00ff'), ('Пурпурный', '#800080'), ('Красный', '#ff0000'), ('Коричнево-малиновый', '#800000'), ('Жёлтый', '#ffff00'), ('Оливковый', '#808000'), ('Лайм', '#00ff00'), ('Зелёный', '#008000'), ('Цвет морской волны', '#00ffff'), ('Окраски птицы чирок', '#008080'), ('Синий', '#0000ff'), ('Форма морских офицеров', '#000080')], max_length=100)),
                ('slug', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.RecipeIngredient', to='api.Ingredient'),
        ),
    ]
