# Generated by Django 3.2.8 on 2021-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#000000', 'Черный'), ('#808080', 'Серый'), ('#c0c0c0', 'Серебряный'), ('#ffffff', 'Белый'), ('#ff00ff', 'Фуксия'), ('#800080', 'Пурпурный'), ('#ff0000', 'Красный'), ('#800000', 'Коричнево-малиновый'), ('#ffff00', 'Жёлтый'), ('#808000', 'Оливковый'), ('#00ff00', 'Лайм'), ('#008000', 'Зелёный'), ('#00ffff', 'Цвет морской волны'), ('#008080', 'Окраски птицы чирок'), ('#0000ff', 'Синий'), ('#000080', 'Форма морских офицеров')], max_length=100),
        ),
    ]
