# Generated by Django 3.2.8 on 2021-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartshopping_favoriterecipe_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
