# Generated by Django 3.2.8 on 2021-10-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartshopping',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cartshopping',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='api.recipe'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='api.recipe'),
            preserve_default=False,
        ),
    ]
